name: CI

on: [push]

jobs:
    build:
        name: Validation
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn
            - name: Lint validation
              run: yarn lint
            - name: TS Compilation
              run: yarn build
